In [1]:
import numpy as np

arr = np.arange(20)
print(arr)

input_bars_for_predicate = 10  #　この先何本分を予測するか。

print('------ 過去のデータを抽出 datasetは既に標準値化済み ------')
dataset_input = arr[input_bars_for_predicate*-1:]
print(dataset_input)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------ 過去のデータを抽出 datasetは既に標準値化済み ------
[10 11 12 13 14 15 16 17 18 19]


In [2]:
print(dataset_input[-5:])

[15 16 17 18 19]
